{"hierarchy":{"paths":[[]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"content","content":[{"type":"heading","level":2,"text":"Note","anchor":"Note"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To use the ADITION AdSDK the application developer will need to acquire the AdSDK library as well as "},{"code":"networkId","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"contentUnit","type":"codeVoice"},{"text":" pairs from an ADITION customer.","type":"text"}]},{"inlineContent":[{"text":"If your experience “cannot load page” errors when navigating between entries in this documentation, then the culprit is very likely an activated ad blocker. Many of the documented classes and services have names related to advertising terms. We found that this can trigger ad blockers. So please disable your adblocker if you have issues.","type":"text"}],"type":"paragraph"},{"text":"Overview","type":"heading","level":2,"anchor":"Overview"},{"inlineContent":[{"type":"text","text":"To serve advertisements using the Adition AdSDK you will typically:"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Add the package dependencies (public, without dSYM) or integrate xcframework via Nexus (with dSYM)."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Initialize and configure the ","type":"text"},{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService","isActive":true,"type":"reference"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Request the creation of an ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/Advertisement","isActive":true},{"type":"text","text":" from "},{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService","isActive":true,"type":"reference"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Observe ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdState","isActive":true},{"type":"text","text":" and "},{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdEvent","isActive":true},{"text":".","type":"text"}]}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"text":"Apps using this AdSDK must be built at least for deployment target of iOS 14.0.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can follow the AdSDK integration "},{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/tutorials\/Meet-AdSDK","overridingTitleInlineContent":[{"text":"tutorial","type":"text"}],"isActive":true,"overridingTitle":"tutorial"},{"text":" with code examples where you will create your first application using the AdSDK.","type":"text"}]},{"type":"heading","anchor":"Tracking-Transparency","text":"Tracking Transparency","level":3},{"type":"paragraph","inlineContent":[{"text":"Starting with IOS 14, you, as a developer, are required to ask for permission to track a user. Learn more in Apple’s ","type":"text"},{"identifier":"https:\/\/developer.apple.com\/app-store\/user-privacy-and-data-use","type":"reference","isActive":true},{"type":"text","text":"."}]},{"inlineContent":[{"type":"text","text":"The SDK offers a wide range of functionality that can be used for tracking. If you use tracking in your application, you are responsible for:"}],"type":"paragraph"},{"inlineContent":[{"type":"strong","inlineContent":[{"text":"1. Adding a privacy manifest to your project.","type":"text"}]}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Learn more in Apple’s "},{"identifier":"https:\/\/developer.apple.com\/documentation\/bundleresources\/privacy_manifest_files\/describing_data_use_in_privacy_manifests","type":"reference","isActive":true},{"type":"text","text":". Apple requires some kind of domain related to tracking. You can use the following domain as a tracking domain: "},{"code":"adition.com","type":"codeVoice"},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"text":"2. Passing ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest\/GlobalParameters\/isOptOutEnabled"}]},{"type":"text","text":"."}]},{"inlineContent":[{"type":"text","text":"Even if the user denies the tracking, IOS will not block URL requests for "},{"code":"adition.com","type":"codeVoice"},{"text":" domain from the SDK. In addition to adding this domain to the privacy manifest, you should pass the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest\/GlobalParameters\/isOptOutEnabled","type":"reference"},{"type":"text","text":" parameter to the SDK if the user has denied tracking. You can do this using the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService\/setGlobalParameter(_:_:)"},{"text":" method.","type":"text"}],"type":"paragraph"},{"text":"Important Classes & Functions","type":"heading","anchor":"Important-Classes--Functions","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"When dealing with Ads you will interact with the following API:"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService","isActive":true},{"type":"text","text":" – core SDK’s interface."}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"overridingTitleInlineContent":[{"text":"configure(networkID:,cacheSize:,timeout:)","type":"text"}],"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdSDKSwiftUI#AdService-creation-for-SwiftUI","isActive":true,"overridingTitle":"configure(networkID:,cacheSize:,timeout:)"},{"type":"text","text":" – a static method that includes creating and configuring the "},{"isActive":true,"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService","type":"reference"},{"text":", registering native renderers, and setting the cache size.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService\/makeAdvertisement(request:placementType:targetURLHandler:)","isActive":true},{"text":" – creating an ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/Advertisement"},{"type":"text","text":" object with inline or interstitial placement type and initiating a request to the ad server."}]}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/Advertisement","isActive":true},{"text":" – represents an advertisement.","type":"text"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdState","type":"reference"},{"type":"text","text":" - represents the lifecycle states of an Advertisements ("},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdState\/loading"},{"type":"text","text":", "},{"isActive":true,"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdState\/caching","type":"reference"},{"type":"text","text":", "},{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdState\/readyToPresent(metadata:)","isActive":true},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdState\/error(_:)"},{"text":".","type":"text"}]}]},{"content":[{"inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdEvent","type":"reference"},{"type":"text","text":" – represents tracking events triggered when an advertisement is served, displayed or users interact with it"}],"type":"paragraph"}]}],"type":"unorderedList"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","overridingTitleInlineContent":[{"text":"AdView","type":"text"}],"isActive":true,"overridingTitle":"AdView","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdSDKSwiftUI#Displaying-Inline-Advertisements"},{"type":"text","text":" – while "},{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/Advertisement","type":"reference","isActive":true},{"type":"text","text":" represents the content and state of an advertisement, "},{"code":"AdView","type":"codeVoice"},{"type":"text","text":" is the element for displaying inline ad on a view hierarchy."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"overridingTitleInlineContent":[{"type":"text","text":"View.interstitial(isShouldBePresented:,_:)"}],"isActive":true,"overridingTitle":"View.interstitial(isShouldBePresented:,_:)","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdSDKSwiftUI#Displaying-Interstitial-Advertisements","type":"reference"},{"type":"text","text":" – while "},{"code":"Advertisement","type":"codeVoice"},{"text":" represents the content and state of an advertisement, ","type":"text"},{"type":"codeVoice","code":".interstitial(isShouldBePresented:,_:)"},{"text":" is the element for displaying interstitial ad as a full screen cover.","type":"text"}]}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To gain a more detailed understanding of how to work with these objects and how they are related, we recommend going through our "},{"type":"reference","isActive":true,"overridingTitleInlineContent":[{"type":"text","text":"tutorial"}],"identifier":"doc:\/\/com.adsdk.core\/tutorials\/Meet-AdSDK","overridingTitle":"tutorial"},{"type":"text","text":"."}]},{"type":"heading","anchor":"SDK-Error-Type","text":"SDK Error Type","level":2},{"inlineContent":[{"type":"text","text":"If you are not using Custom Native Renderers with your custom error types, all errors related to the SDK can be converted to the "},{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdError","isActive":true},{"type":"text","text":" type."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"You can find all the errors that the SDK may return in the documentation to the ","type":"text"},{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdError","isActive":true,"type":"reference"},{"type":"text","text":"."}]},{"text":"Explaining the concepts of AdSDK server requests","level":2,"type":"heading","anchor":"Explaining-the-concepts-of-AdSDK-server-requests"},{"inlineContent":[{"text":"Your app uses the AdSDK to request ads from an ad server.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To enable the ad server to serve relevant ads, you must pass certain information. The first argument you will pass when creating an "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService"},{"type":"text","text":" is the "},{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService\/networkID","isActive":true,"type":"reference"},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"text":"When creating an ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/Advertisement","isActive":true},{"type":"text","text":", you can pass additional information through "},{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService\/makeAdvertisement(request:placementType:targetURLHandler:)","isActive":true},{"text":":","type":"text"}]},{"items":[{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdPlacementType","isActive":true},{"text":" (required)","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest\/contentUnit","isActive":true},{"type":"text","text":" (required)"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest\/profile"},{"text":" (optional)","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest\/keywords"},{"text":" (optional)","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest\/window","type":"reference","isActive":true},{"text":" (optional)","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest\/gdprPd","isActive":true},{"type":"text","text":" (optional)"}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest\/timeoutAfterSeconds","type":"reference","isActive":true},{"type":"text","text":" (optional)"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest\/campaignId","type":"reference"},{"type":"text","text":" (optional)"}]}]},{"content":[{"inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest\/bannerId","type":"reference"},{"text":" (optional)","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"},{"inlineContent":[{"text":"Some parameters of ","type":"text"},{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest","isActive":true,"type":"reference"},{"text":" are designed to be passed in all requests, not just individual ones. To avoid duplicating code, SDK provide ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService\/setGlobalParameter(_:_:)"},{"type":"text","text":" and "},{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService\/removeGlobalParameter(_:)","type":"reference","isActive":true},{"text":" methods, which will modify these optional parameters:","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest\/GlobalParameters\/gdpr","isActive":true}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest\/GlobalParameters\/externalUID","isActive":true}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest\/GlobalParameters\/isOptOutEnabled","isActive":true}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest\/GlobalParameters\/isSHBEnabled","isActive":true}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest\/GlobalParameters\/userIds"}]}]}]},{"inlineContent":[{"type":"text","text":"By default, the SDK opens an external browser when processing a target URL. You can override this behaviour with your own. For example, this can be useful if you want to open your internal browser in your application to process the target URL. To do this, you pass the "},{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/TargetURLHandler","isActive":true},{"type":"text","text":" to the "},{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService\/makeAdvertisement(request:placementType:targetURLHandler:)","isActive":true},{"text":" method.","type":"text"}],"type":"paragraph"},{"anchor":"State--Events","text":"State & Events","type":"heading","level":2},{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/Advertisement","isActive":true},{"type":"text","text":" will emit two types of events:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Lifecycle events:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdState\/loading"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdState\/caching","isActive":true}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdState\/readyToPresent(metadata:)","isActive":true}]}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdState\/error(_:)","isActive":true}],"type":"paragraph"}]}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"See "},{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdState","isActive":true},{"text":" for more details.","type":"text"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Tracking events:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdEvent\/tap(url:metadata:)","isActive":true}]}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdEvent\/impression(url:metadata:)","isActive":true}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdEvent\/viewable(percentage:url:metadata:)","isActive":true,"type":"reference"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdEvent\/showingAsset(id:url:metadata:)","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdEvent\/unloadRequest"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdEvent\/customRendererEvent(name:url:info:metadata:)"}]}]}]}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"type":"text","text":"See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdEvent"},{"type":"text","text":" for more details."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"To enable the partial visibility events "},{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdEvent\/viewable(percentage:url:metadata:)","isActive":true,"type":"reference"},{"type":"text","text":" with inline ad, you have to add the "},{"type":"codeVoice","code":".adsContainer()"},{"text":" modifier. See more in ","type":"text"},{"type":"reference","overridingTitleInlineContent":[{"text":"AdSDKSwiftUI documentation","type":"text"}],"overridingTitle":"AdSDKSwiftUI documentation","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdSDKSwiftUI#Visibility-events","isActive":true},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"text":"Which tracking events are enabled for which Advertisements is configured in the ADITION Backend.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"To gain a more detailed understanding of how to work with state and events, we recommend going through our "},{"overridingTitleInlineContent":[{"type":"text","text":"tutorial"}],"isActive":true,"type":"reference","overridingTitle":"tutorial","identifier":"doc:\/\/com.adsdk.core\/tutorials\/Meet-AdSDK"},{"type":"text","text":"."}]},{"type":"heading","level":2,"text":"Handling inApp-ClickURL","anchor":"Handling-inApp-ClickURL"},{"type":"paragraph","inlineContent":[{"text":"inApp-ClickURLs is a feature which allows you to specify a custom schemed click url. An example of a custom scheme url is ","type":"text"},{"type":"codeVoice","code":"myschema:\/\/coupons"},{"text":". Banners with this option selected will not open a browser when it is clicked. If an app is installed on the device for the given URL schema, then this app will be opened to process the URL.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"The ADITION click counting works by initially calling the ad server url which will then count the click and redirect to the banner click url. By default this is done by the built-in ADITION browser. The exception to this default click handling is with inApp-ClickURL banners, as they are handled by the SDK internally which ensures the click is successfully counted and the intent fired.","type":"text"}]},{"anchor":"Tagging-request","text":"Tagging request","level":2,"type":"heading"},{"inlineContent":[{"text":"Tagging targeting is a server side tagging (user profile) feature. You are able to tag a user currently using your application with key = value tags that can be used in targeting of campaigns within the ADITION ad serving platform.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"See ","type":"text"},{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/TagRequest","isActive":true,"type":"reference"},{"type":"text","text":". This structure uses as a parameter the "},{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService\/tagUser(request:)-2remz","isActive":true},{"type":"text","text":" (Combine) and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService\/tagUser(request:)-4qs0m"},{"type":"text","text":" (Async\/Await) methods. You can pass all tags through the initializer."}],"type":"paragraph"},{"text":"Tracking request","anchor":"Tracking-request","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Tracking is a server side feature. You are able to perform tracking request to track your conversions."}]},{"type":"paragraph","inlineContent":[{"text":"See ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/TrackRequest","isActive":true},{"type":"text","text":". The app can fire the track request as soon as a conversion occurs within the app. See "},{"isActive":true,"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService\/trackRequest(_:)-9icj3","type":"reference"},{"text":" (Combine) and ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService\/trackRequest(_:)-1w1d2"},{"text":" (Async\/Await).","type":"text"}]},{"type":"heading","level":2,"text":"Manual tap event triggering","anchor":"Manual-tap-event-triggering"},{"type":"paragraph","inlineContent":[{"text":"There is function called ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/Advertisement\/performTapEvent(_:)"},{"type":"text","text":", responsible for performing any kind of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/TapEvent"},{"text":". This function use for app developer when they need to call tap event manually.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"Performable tap events:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/TapEvent\/tap","type":"reference","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/TapEvent\/tapURL(_:)","isActive":true,"type":"reference"}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/TapEvent\/tapAsset(id:)","isActive":true,"type":"reference"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/TapEvent\/silentTap(_:)","isActive":true}],"type":"paragraph"}]}]},{"text":"Creating custom native Ads","type":"heading","anchor":"Creating-custom-native-Ads","level":2},{"inlineContent":[{"type":"text","text":"As App developer, you can create your own custom ad formats. For example, you can implement interactive ad formats like surveys, rotating galleries or Ads that play video."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Your custom ad format can be configured in the Adition backend. There you can define a creative template with custom JSON that will be delivered as part of the ad. For example, you could provide a way to configure some styling aspects for the ad by adding custom JSON key-value-pairs to the creative template. On the app side, you can implement your custom Ad with native technologies like Swift and SwiftUI."}]},{"type":"paragraph","inlineContent":[{"text":"As part of your custom ad you will need to provide:","type":"text"}]},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"a controller class which implements the  "},{"isActive":true,"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdController","type":"reference"},{"text":" protocol;","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"a view class which implements the "},{"isActive":true,"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRenderer","type":"reference"},{"text":" protocol.","type":"text"}]}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To make the SDK aware of your ad, you need to register it with the SDK using "},{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService\/registerRenderer(_:forName:)","isActive":true},{"type":"text","text":". Once your custom ad is registered, the SDK will  signal the Adition ad server that it can handle this new ad format for  subsequent ad request. The SDK will also manage the creation of the instances of your controller and view classes in case actual ad content is delivered by the ad server."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Your controller class needs to implement the "},{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdController\/update(_:_:)","isActive":true},{"type":"text","text":" method of the "},{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdController","isActive":true},{"text":" protocol. This method will be called every time ","type":"text"},{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/Advertisement","type":"reference","isActive":true},{"type":"text","text":" manages to load advertisement data. In it you can process the data, and prepare the "},{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRenderer","type":"reference","isActive":true},{"type":"text","text":" for display."}]},{"inlineContent":[{"type":"text","text":"Your controller and the SDK communicate with each other using events and states, see "},{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdControllerEvent","isActive":true},{"type":"text","text":" and "},{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdControllerState","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"You can find an example of the implementation of both controllers and views for custom ads in the documentation for ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdController"},{"type":"text","text":" and "},{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRenderer","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}]}],"variants":[{"paths":["\/documentation\/adsdkcore"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/adsdkcore"]}],"topicSections":[{"title":"Essentials","identifiers":["doc:\/\/com.adsdk.core\/tutorials\/Meet-AdSDK","doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService","doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/Advertisement","doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdSDKSwiftUI"],"anchor":"Essentials"},{"title":"Advertisement Creation","identifiers":["doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService\/makeAdvertisement(request:placementType:targetURLHandler:)","doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest","doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest\/GlobalParameters","doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/TargetURLHandler","doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdPlacementType"],"anchor":"Advertisement-Creation"},{"anchor":"State--Events-Handling","identifiers":["doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdState","doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdEvent","doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/Advertisement\/statePublisher","doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/Advertisement\/stateStream","doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/Advertisement\/state","doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/Advertisement\/eventPublisher","doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/Advertisement\/eventStream","doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdMetadata","doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdError","doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdVisibilityPercentage","doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/TapURL"],"title":"State & Events Handling"},{"anchor":"Tap-Events-Triggering","identifiers":["doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/TapEvent","doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/Advertisement\/performTapEvent(_:)"],"title":"Tap Events Triggering"},{"title":"Track Request","anchor":"Track-Request","identifiers":["doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/TrackRequest","doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService\/trackRequest(_:)-9icj3","doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService\/trackRequest(_:)-1w1d2"]},{"identifiers":["doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/TagRequest","doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService\/tagUser(request:)-2remz","doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService\/tagUser(request:)-4qs0m"],"anchor":"Tag-Request","title":"Tag Request"},{"anchor":"Creating-Custom-Native-Ad","title":"Creating Custom Native Ad","identifiers":["doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdController","doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRenderer","doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdControllerState","doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdControllerEvent","doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService\/registerRenderer(_:forName:)","doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService\/unregisterRenderer(forName:)"]},{"anchor":"Custom-Native-Ad-Assets-Caching","identifiers":["doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AssetRepository","doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AssetRepositoryState","doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AssetRequest","doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AssetResult"],"title":"Custom Native Ad Assets Caching"}],"identifier":{"url":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Manage, display, and create your custom advertisements on iOS using cutting-edge technologies such as Combine, Modern Concurrency, and SwiftUI based."}],"metadata":{"title":"AdSDKCore","externalID":"AdSDKCore","symbolKind":"module","role":"collection","modules":[{"name":"AdSDKCore"}],"roleHeading":"Framework"},"sections":[],"references":{"doc://com.adsdk.core/documentation/AdSDKCore/AdService/trackRequest(_:)-1w1d2":{"type":"topic","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService\/trackRequest(_:)-1w1d2","role":"symbol","kind":"symbol","abstract":[{"text":"Trigger a request for conversion tracking.","type":"text"}],"title":"trackRequest(_:)","url":"\/documentation\/adsdkcore\/adservice\/trackrequest(_:)-1w1d2","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackRequest"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:9AdSDKCore12TrackRequestV","text":"TrackRequest","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}]},"doc://com.adsdk.core/documentation/AdSDKCore/Advertisement/performTapEvent(_:)":{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/Advertisement\/performTapEvent(_:)","url":"\/documentation\/adsdkcore\/advertisement\/performtapevent(_:)","type":"topic","kind":"symbol","title":"performTapEvent(_:)","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"performTapEvent","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:9AdSDKCore8TapEventO","text":"TapEvent"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This function is responsible for firing the tap event manually."}]},"doc://com.adsdk.core/documentation/AdSDKCore/Advertisement/state":{"title":"state","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:9AdSDKCore0A5StateO","text":"AdState","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/adsdkcore\/advertisement\/state","required":true,"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/Advertisement\/state","abstract":[{"text":"Current ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdState"},{"text":" of ","type":"text"},{"code":"Advertisement","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol"},"doc://com.adsdk.core/documentation/AdSDKCore/AdEvent/viewable(percentage:url:metadata:)":{"url":"\/documentation\/adsdkcore\/adevent\/viewable(percentage:url:metadata:)","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewable"},{"kind":"text","text":"("},{"text":"percentage","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdVisibilityPercentage","preciseIdentifier":"s:9AdSDKCore0A20VisibilityPercentageO"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"url"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:9AdSDKCore0A8MetadataC","text":"AdMetadata"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdEvent\/viewable(percentage:url:metadata:)","abstract":[{"type":"text","text":"Signals that the user has seen an advertisement."}],"kind":"symbol","title":"AdEvent.viewable(percentage:url:metadata:)"},"doc://com.adsdk.core/documentation/AdSDKCore/Advertisement/eventPublisher":{"type":"topic","kind":"symbol","title":"eventPublisher","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventPublisher"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7Combine12AnyPublisherV","text":"AnyPublisher","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:9AdSDKCore0A5EventO","text":"AdEvent","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"Never","kind":"typeIdentifier","preciseIdentifier":"s:s5NeverO"},{"text":">","kind":"text"}],"url":"\/documentation\/adsdkcore\/advertisement\/eventpublisher","abstract":[{"type":"text","text":"Advertisement event publisher."}],"role":"symbol","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/Advertisement\/eventPublisher"},"doc://com.adsdk.core/documentation/AdSDKCore/AdSDKCoreVersionNumber":{"role":"symbol","kind":"symbol","abstract":[{"text":"Project version number for AdSDKCore.","type":"text"}],"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdSDKCoreVersionNumber","url":"\/documentation\/adsdkcore\/adsdkcoreversionnumber","title":"AdSDKCoreVersionNumber","type":"topic","fragments":[{"kind":"identifier","text":"AdSDKCoreVersionNumber"}]},"doc://com.adsdk.core/documentation/AdSDKCore/Advertisement/eventStream":{"title":"eventStream","abstract":[{"type":"text","text":"Advertisement async event stream."}],"kind":"symbol","role":"symbol","required":true,"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/Advertisement\/eventStream","type":"topic","url":"\/documentation\/adsdkcore\/advertisement\/eventstream","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"eventStream","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AsyncStream","kind":"typeIdentifier","preciseIdentifier":"s:ScS"},{"text":"<","kind":"text"},{"text":"AdEvent","kind":"typeIdentifier","preciseIdentifier":"s:9AdSDKCore0A5EventO"},{"kind":"text","text":">"}]},"https://iabeurope.eu/transparency-consent-framework/":{"type":"link","url":"https:\/\/iabeurope.eu\/transparency-consent-framework\/","titleInlineContent":[{"type":"text","text":"link."}],"identifier":"https:\/\/iabeurope.eu\/transparency-consent-framework\/","title":"link."},"doc://com.adsdk.core/documentation/AdSDKCore/AdPlacementType":{"type":"topic","title":"AdPlacementType","navigatorTitle":[{"text":"AdPlacementType","kind":"identifier"}],"abstract":[{"text":"Enum describing the expected type of placement for the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/Advertisement","type":"reference"},{"type":"text","text":"."}],"role":"symbol","url":"\/documentation\/adsdkcore\/adplacementtype","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdPlacementType","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdPlacementType","kind":"identifier"}]},"doc://com.adsdk.core/documentation/AdSDKCore/AdState/caching":{"role":"symbol","kind":"symbol","abstract":[{"text":"Signals that the advertisement assets are currently being cached.","type":"text"}],"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdState\/caching","url":"\/documentation\/adsdkcore\/adstate\/caching","title":"AdState.caching","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"caching","kind":"identifier"}]},"doc://com.adsdk.core/documentation/AdSDKCore/AdRequest/contentUnit":{"url":"\/documentation\/adsdkcore\/adrequest\/contentunit","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentUnit"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest\/contentUnit","abstract":[{"type":"text","text":"Unique ID of a content space in the ADITION ad-serving platform."}],"kind":"symbol","title":"contentUnit"},"doc://com.adsdk.core/documentation/AdSDKCore/AdRequest/UserIdType":{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest\/UserIdType","title":"AdRequest.UserIdType","role":"symbol","navigatorTitle":[{"text":"UserIdType","kind":"identifier"}],"abstract":[{"type":"text","text":"This enum is a list of the user ID types that the SDK supports."}],"url":"\/documentation\/adsdkcore\/adrequest\/useridtype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserIdType"}],"type":"topic","kind":"symbol"},"doc://com.adsdk.core/documentation/AdSDKCore/AdService/registerRenderer(_:forName:)":{"title":"registerRenderer(_:forName:)","type":"topic","role":"symbol","url":"\/documentation\/adsdkcore\/adservice\/registerrenderer(_:forname:)","abstract":[{"type":"text","text":"Registers a custom ad renderer."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerRenderer"},{"text":"<","kind":"text"},{"kind":"genericParameter","text":"T"},{"text":">(","kind":"text"},{"kind":"typeIdentifier","text":"T","preciseIdentifier":"s:9AdSDKCore0A7ServiceC16registerRenderer_7forNameyxm_SStAA0aE0RzlF1TL_xmfp"},{"kind":"text","text":".Type, "},{"text":"forName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService\/registerRenderer(_:forName:)"},"doc://com.adsdk.core/documentation/AdSDKCore/AdRequest/GlobalParameters/userIds":{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest\/GlobalParameters\/userIds","title":"userIds","role":"symbol","abstract":[{"type":"text","text":"The data type of the userId is an array with the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest\/UserIdType"},{"text":" enum values.","type":"text"}],"url":"\/documentation\/adsdkcore\/adrequest\/globalparameters\/userids","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userIds","kind":"identifier"},{"text":": [","kind":"text"},{"text":"UserIdType","kind":"typeIdentifier","preciseIdentifier":"s:9AdSDKCore0A7RequestV10UserIdTypeO"},{"kind":"text","text":"]?"}],"type":"topic","kind":"symbol"},"doc://com.adsdk.core/documentation/AdSDKCore/AdRequest/gdprPd":{"url":"\/documentation\/adsdkcore\/adrequest\/gdprpd","type":"topic","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest\/gdprPd","abstract":[{"text":"If your app passes personal information as part of the user profiles,","type":"text"},{"type":"text","text":" "},{"text":"you can set an ","type":"text"},{"type":"codeVoice","code":"gdprPd"},{"text":" parameter when creating an ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/Advertisement","isActive":true},{"type":"text","text":"."}],"kind":"symbol","title":"gdprPd","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gdprPd","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":"?"}],"role":"symbol"},"doc://com.adsdk.core/documentation/AdSDKCore/AdService/networkID":{"title":"networkID","abstract":[{"text":"The unique identifier of the ad network.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"networkID","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"type":"topic","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService\/networkID","kind":"symbol","role":"symbol","url":"\/documentation\/adsdkcore\/adservice\/networkid"},"doc://com.adsdk.core/documentation/AdSDKCore":{"url":"\/documentation\/adsdkcore","kind":"symbol","title":"AdSDKCore","abstract":[{"type":"text","text":"Manage, display, and create your custom advertisements on iOS using cutting-edge technologies such as Combine, Modern Concurrency, and SwiftUI based."}],"type":"topic","role":"collection","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore"},"doc://com.adsdk.core/documentation/AdSDKCore/TrackRequest":{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/TrackRequest","abstract":[{"type":"text","text":"Trigger a request for conversion tracking."}],"role":"symbol","url":"\/documentation\/adsdkcore\/trackrequest","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TrackRequest"}],"title":"TrackRequest","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TrackRequest"}]},"doc://com.adsdk.core/documentation/AdSDKCore/AdService/makeAdvertisement(request:placementType:targetURLHandler:)":{"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/adsdkcore\/adservice\/makeadvertisement(request:placementtype:targeturlhandler:)","abstract":[{"text":"Creating an ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/Advertisement","isActive":true},{"text":" object and performing ad request.","type":"text"}],"title":"makeAdvertisement(request:placementType:targetURLHandler:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeAdvertisement"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"request"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AdRequest","preciseIdentifier":"s:9AdSDKCore0A7RequestV"},{"kind":"text","text":", "},{"text":"placementType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:9AdSDKCore0A13PlacementTypeO","text":"AdPlacementType"},{"kind":"text","text":", "},{"text":"targetURLHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TargetURLHandler","kind":"typeIdentifier","preciseIdentifier":"s:9AdSDKCore16TargetURLHandlerP"},{"text":"?) -> ","kind":"text"},{"text":"Advertisement","kind":"typeIdentifier","preciseIdentifier":"s:9AdSDKCore13AdvertisementP"}],"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService\/makeAdvertisement(request:placementType:targetURLHandler:)"},"doc://com.adsdk.core/documentation/AdSDKCore/AssetRepositoryState":{"url":"\/documentation\/adsdkcore\/assetrepositorystate","title":"AssetRepositoryState","navigatorTitle":[{"kind":"identifier","text":"AssetRepositoryState"}],"abstract":[{"type":"text","text":"Interface to encapsulate "},{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdControllerState","isActive":true,"type":"reference"},{"type":"text","text":"."}],"type":"topic","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AssetRepositoryState","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AssetRepositoryState","kind":"identifier"}]},"doc://com.adsdk.core/documentation/AdSDKCore/AdRequest/bannerId":{"type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bannerId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/adsdkcore\/adrequest\/bannerid","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest\/bannerId","abstract":[{"text":"The SDK provides functionality to request a specific banner from the backend.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This could be helpful for debugging and testing purposes."}],"title":"bannerId","kind":"symbol"},"doc://com.adsdk.core/documentation/AdSDKCore/AssetResult":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"AssetResult"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"AssetResult","kind":"identifier"}],"abstract":[{"type":"text","text":"Result of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AssetRepository\/loadAssets(_:stateSubject:)"},{"type":"text","text":" method."}],"title":"AssetResult","role":"symbol","kind":"symbol","url":"\/documentation\/adsdkcore\/assetresult","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AssetResult"},"doc://com.adsdk.core/documentation/AdSDKCore/AdMetadata":{"kind":"symbol","url":"\/documentation\/adsdkcore\/admetadata","type":"topic","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdMetadata","title":"AdMetadata","abstract":[{"text":"A class that contains the basic data about the advertisement and renderer.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AdMetadata","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AdMetadata"}]},"doc://com.adsdk.core/documentation/AdSDKCore/TagRequest":{"abstract":[{"text":"Describes a request to “tag” a user.","type":"text"}],"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/TagRequest","title":"TagRequest","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"TagRequest","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"TagRequest","kind":"identifier"}],"type":"topic","url":"\/documentation\/adsdkcore\/tagrequest"},"doc://com.adsdk.core/documentation/AdSDKCore/AdState/error(_:)":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}],"title":"AdState.error(_:)","url":"\/documentation\/adsdkcore\/adstate\/error(_:)","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdState\/error(_:)","type":"topic","abstract":[{"type":"text","text":"Signals that an advertisement lifecycle error has occurred."}]},"doc://com.adsdk.core/documentation/AdSDKCore/AdService/unregisterRenderer(forName:)":{"abstract":[{"type":"text","text":"Unregisters the custom ad renderer."}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService\/unregisterRenderer(forName:)","url":"\/documentation\/adsdkcore\/adservice\/unregisterrenderer(forname:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unregisterRenderer","kind":"identifier"},{"kind":"text","text":"("},{"text":"forName","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"unregisterRenderer(forName:)"},"doc://com.adsdk.core/documentation/AdSDKCore/AdRequest/GlobalParameters/isOptOutEnabled":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isOptOutEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?"}],"role":"symbol","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest\/GlobalParameters\/isOptOutEnabled","type":"topic","title":"isOptOutEnabled","url":"\/documentation\/adsdkcore\/adrequest\/globalparameters\/isoptoutenabled","abstract":[{"type":"text","text":"An app can ask users if they want to opt out from process data. Use this configuration"},{"text":" ","type":"text"},{"text":"to make the users choice visible for the ad server.","type":"text"}],"kind":"symbol"},"doc://com.adsdk.core/documentation/AdSDKCore/AdRequest/profile":{"kind":"symbol","type":"topic","url":"\/documentation\/adsdkcore\/adrequest\/profile","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest\/profile","abstract":[{"type":"text","text":"When requesting an advertisement it is possible to send application targeting profiles which can"},{"type":"text","text":" "},{"type":"text","text":"be used to select the correct banner that should be delivered."}],"title":"profile","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"profile"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]?","kind":"text"}]},"doc://com.adsdk.core/documentation/AdSDKCore/AdService/setGlobalParameter(_:_:)":{"abstract":[{"text":"A method for setting global parameters for ","type":"text"},{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest","isActive":true,"type":"reference"},{"type":"text","text":" before calling"},{"text":" ","type":"text"},{"type":"text","text":"the "},{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService\/makeAdvertisement(request:placementType:targetURLHandler:)","isActive":true},{"type":"text","text":" "},{"type":"text","text":"method."}],"type":"topic","title":"setGlobalParameter(_:_:)","kind":"symbol","url":"\/documentation\/adsdkcore\/adservice\/setglobalparameter(_:_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setGlobalParameter","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"kind":"text","text":">("},{"text":"WritableKeyPath","kind":"typeIdentifier","preciseIdentifier":"s:s15WritableKeyPathC"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:9AdSDKCore0A7RequestV","text":"AdRequest","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"GlobalParameters","preciseIdentifier":"s:9AdSDKCore0A7RequestV16GlobalParametersV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"T","preciseIdentifier":"s:9AdSDKCore0A7ServiceC18setGlobalParameteryys15WritableKeyPathCyAA0A7RequestV0E10ParametersVxSgG_AKtlF1TL_xmfp"},{"text":"?>, ","kind":"text"},{"preciseIdentifier":"s:9AdSDKCore0A7ServiceC18setGlobalParameteryys15WritableKeyPathCyAA0A7RequestV0E10ParametersVxSgG_AKtlF1TL_xmfp","text":"T","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService\/setGlobalParameter(_:_:)"},"doc://com.adsdk.core/documentation/AdSDKCore/Advertisement/stateStream":{"kind":"symbol","url":"\/documentation\/adsdkcore\/advertisement\/statestream","type":"topic","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/Advertisement\/stateStream","required":true,"title":"stateStream","abstract":[{"text":"Advertisement async state stream.","type":"text"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"stateStream","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:ScS","text":"AsyncStream"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:9AdSDKCore0A5StateO","text":"AdState","kind":"typeIdentifier"},{"text":">","kind":"text"}]},"doc://com.adsdk.core/documentation/AdSDKCore/AdRequest/timeoutAfterSeconds":{"title":"timeoutAfterSeconds","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"timeoutAfterSeconds","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"type":"topic","url":"\/documentation\/adsdkcore\/adrequest\/timeoutafterseconds","abstract":[{"type":"text","text":"Timeout for specific "},{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest","isActive":true,"type":"reference"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest\/timeoutAfterSeconds","kind":"symbol"},"doc://com.adsdk.core/documentation/AdSDKCore/AdSDKSwiftUI#Displaying-Interstitial-Advertisements":{"url":"\/documentation\/adsdkcore\/adsdkswiftui#Displaying-Interstitial-Advertisements","title":"Displaying Interstitial Advertisements","type":"topic","abstract":[],"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdSDKSwiftUI#Displaying-Interstitial-Advertisements","kind":"section"},"doc://com.adsdk.core/documentation/AdSDKCore/AdRequest/keywords":{"type":"topic","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest\/keywords","abstract":[{"type":"text","text":"The keyword targeting is a simple comma separated list of keywords that can be"},{"type":"text","text":" "},{"type":"text","text":"used to make partial or complete keyword list targeting."}],"kind":"symbol","role":"symbol","url":"\/documentation\/adsdkcore\/adrequest\/keywords","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keywords","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"]?","kind":"text"}],"title":"keywords"},"doc://com.adsdk.core/documentation/AdSDKCore/TapEvent":{"abstract":[{"type":"text","text":"Public enum describing all tap events that can be processed by the SDK."}],"navigatorTitle":[{"text":"TapEvent","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/adsdkcore\/tapevent","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/TapEvent","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TapEvent"}],"title":"TapEvent"},"doc://com.adsdk.core/documentation/AdSDKCore/AdSDKSwiftUI#Visibility-events":{"url":"\/documentation\/adsdkcore\/adsdkswiftui#Visibility-events","title":"Visibility events","type":"topic","abstract":[],"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdSDKSwiftUI#Visibility-events","kind":"section"},"doc://com.adsdk.core/documentation/AdSDKCore/AdEvent/showingAsset(id:url:metadata:)":{"role":"symbol","abstract":[{"type":"text","text":"Signals that the renderer is currently showing a particular asset."}],"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdEvent\/showingAsset(id:url:metadata:)","kind":"symbol","url":"\/documentation\/adsdkcore\/adevent\/showingasset(id:url:metadata:)","title":"AdEvent.showingAsset(id:url:metadata:)","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"showingAsset"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"url"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"metadata"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AdMetadata","preciseIdentifier":"s:9AdSDKCore0A8MetadataC"},{"text":")","kind":"text"}]},"doc://com.adsdk.core/documentation/AdSDKCore/AdControllerState":{"abstract":[{"text":"Enumeration of the possible states of the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdController","isActive":true},{"text":".","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdControllerState","url":"\/documentation\/adsdkcore\/adcontrollerstate","kind":"symbol","title":"AdControllerState","navigatorTitle":[{"kind":"identifier","text":"AdControllerState"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AdControllerState","kind":"identifier"}]},"doc://com.adsdk.core/documentation/AdSDKCore/AdRequest":{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest","title":"AdRequest","role":"symbol","navigatorTitle":[{"text":"AdRequest","kind":"identifier"}],"abstract":[{"type":"text","text":"Describes a request to load an advertisement."}],"url":"\/documentation\/adsdkcore\/adrequest","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdRequest","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.adsdk.core/documentation/AdSDKCore/AdSDKSwiftUI#Displaying-Inline-Advertisements":{"url":"\/documentation\/adsdkcore\/adsdkswiftui#Displaying-Inline-Advertisements","title":"Displaying Inline Advertisements","type":"topic","abstract":[],"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdSDKSwiftUI#Displaying-Inline-Advertisements","kind":"section"},"doc://com.adsdk.core/documentation/AdSDKCore/AssetRepository":{"type":"topic","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AssetRepository","navigatorTitle":[{"text":"AssetRepository","kind":"identifier"}],"abstract":[{"text":"Asset loading service.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/adsdkcore\/assetrepository","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AssetRepository"}],"title":"AssetRepository"},"https://developer.apple.com/app-store/user-privacy-and-data-use":{"title":"documentation","identifier":"https:\/\/developer.apple.com\/app-store\/user-privacy-and-data-use","url":"https:\/\/developer.apple.com\/app-store\/user-privacy-and-data-use","type":"link","titleInlineContent":[{"type":"text","text":"documentation"}]},"doc://com.adsdk.core/documentation/AdSDKCore/AssetRepository/loadAssets(_:stateSubject:)":{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AssetRepository\/loadAssets(_:stateSubject:)","kind":"symbol","title":"loadAssets(_:stateSubject:)","role":"symbol","url":"\/documentation\/adsdkcore\/assetrepository\/loadassets(_:statesubject:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadAssets"},{"text":"<","kind":"text"},{"kind":"genericParameter","text":"T"},{"text":">([","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:9AdSDKCore12AssetRequestV","text":"AssetRequest"},{"text":"], ","kind":"text"},{"text":"stateSubject","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PassthroughSubject","kind":"typeIdentifier","preciseIdentifier":"s:7Combine18PassthroughSubjectC"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:9AdSDKCore15AssetRepositoryP10loadAssets_12stateSubject7Combine12AnyPublisherVySayAA0C6ResultVGAA0A5ErrorOGSayAA0C7RequestVG_AF011PassthroughH0Cyqd__s5NeverOGtAA0cD5StateRd__lF1TL_qd__mfp","kind":"typeIdentifier","text":"T"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:s5NeverO","text":"Never","kind":"typeIdentifier"},{"kind":"text","text":">) -> "},{"text":"AnyPublisher","kind":"typeIdentifier","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"kind":"text","text":"<["},{"text":"AssetResult","kind":"typeIdentifier","preciseIdentifier":"s:9AdSDKCore11AssetResultV"},{"text":"], ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:9AdSDKCore0A5ErrorO","text":"AdError"},{"text":">","kind":"text"}],"abstract":[{"text":"Loads an array of ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AssetResult","isActive":true},{"type":"text","text":" from an "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AssetRequest"},{"type":"text","text":" or retrieves it from the cache."}],"type":"topic","required":true},"doc://com.adsdk.core/documentation/AdSDKCore/AdService/removeGlobalParameter(_:)":{"title":"removeGlobalParameter(_:)","role":"symbol","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService\/removeGlobalParameter(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"removeGlobalParameter","kind":"identifier"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"T"},{"text":">(","kind":"text"},{"preciseIdentifier":"s:s15WritableKeyPathC","kind":"typeIdentifier","text":"WritableKeyPath"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:9AdSDKCore0A7RequestV","text":"AdRequest","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"GlobalParameters","kind":"typeIdentifier","preciseIdentifier":"s:9AdSDKCore0A7RequestV16GlobalParametersV"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:9AdSDKCore0A7ServiceC21removeGlobalParameteryys15WritableKeyPathCyAA0A7RequestV0E10ParametersVxSgGlF1TL_xmfp","text":"T"},{"text":"?>)","kind":"text"}],"url":"\/documentation\/adsdkcore\/adservice\/removeglobalparameter(_:)","type":"topic","abstract":[{"type":"text","text":"A method for removing global parameters for "},{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest","isActive":true,"type":"reference"},{"type":"text","text":"."}]},"doc://com.adsdk.core/documentation/AdSDKCore/AdRequest/GlobalParameters/externalUID":{"abstract":[{"text":"If your app has means to identify a user, for example through association with","type":"text"},{"type":"text","text":" "},{"type":"text","text":"an user account or an advertising ID, you can share this with the ad server."}],"title":"externalUID","type":"topic","kind":"symbol","url":"\/documentation\/adsdkcore\/adrequest\/globalparameters\/externaluid","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"externalUID","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ExternalUID","preciseIdentifier":"s:9AdSDKCore0A7RequestV11ExternalUIDV"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest\/GlobalParameters\/externalUID"},"doc://com.adsdk.core/documentation/AdSDKCore/TapURL":{"kind":"symbol","url":"\/documentation\/adsdkcore\/tapurl","type":"topic","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/TapURL","title":"TapURL","abstract":[{"type":"text","text":"A structure that describes the URL associated with an advertisement tap event."}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TapURL"}],"navigatorTitle":[{"text":"TapURL","kind":"identifier"}]},"doc://com.adsdk.core/documentation/AdSDKCore/TapEvent/tap":{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/TapEvent\/tap","url":"\/documentation\/adsdkcore\/tapevent\/tap","type":"topic","kind":"symbol","title":"TapEvent.tap","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"tap","kind":"identifier"}],"abstract":[{"type":"text","text":"An event that handles the tap on the ad by the user."}]},"doc://com.adsdk.core/documentation/AdSDKCore/AdEvent/tap(url:metadata:)":{"type":"topic","title":"AdEvent.tap(url:metadata:)","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tap","kind":"identifier"},{"text":"(","kind":"text"},{"text":"url","kind":"externalParam"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"metadata"},{"kind":"text","text":": "},{"text":"AdMetadata","preciseIdentifier":"s:9AdSDKCore0A8MetadataC","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","url":"\/documentation\/adsdkcore\/adevent\/tap(url:metadata:)","abstract":[{"text":"Signals that the user has tapped an advertisement.","type":"text"}],"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdEvent\/tap(url:metadata:)"},"doc://com.adsdk.core/documentation/AdSDKCore/AdController":{"url":"\/documentation\/adsdkcore\/adcontroller","kind":"symbol","title":"AdController","type":"topic","abstract":[{"type":"text","text":"Controller interface for custom renderer."}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"AdController","kind":"identifier"}],"navigatorTitle":[{"text":"AdController","kind":"identifier"}],"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdController"},"doc://com.adsdk.core/documentation/AdSDKCore/AdControllerEvent":{"navigatorTitle":[{"text":"AdControllerEvent","kind":"identifier"}],"abstract":[{"text":"Representation of user actions that can be triggered on an ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRenderer"},{"text":".","type":"text"}],"url":"\/documentation\/adsdkcore\/adcontrollerevent","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdControllerEvent","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AdControllerEvent","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","title":"AdControllerEvent"},"doc://com.adsdk.core/documentation/AdSDKCore/AdRequest/window":{"abstract":[{"type":"text","text":"The SDK provides functionality to organize window ids so that inclusion and exclusion filters can"},{"type":"text","text":" "},{"type":"text","text":"be evaluated."}],"role":"symbol","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest\/window","kind":"symbol","type":"topic","url":"\/documentation\/adsdkcore\/adrequest\/window","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"window","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt32V","text":"UInt32","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"window"},"doc://com.adsdk.core/documentation/AdSDKCore/AdEvent/impression(url:metadata:)":{"role":"symbol","abstract":[{"type":"text","text":"Signals that the advertisement is ready to be displayed to the user."}],"type":"topic","url":"\/documentation\/adsdkcore\/adevent\/impression(url:metadata:)","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"impression"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"url"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"metadata"},{"text":": ","kind":"text"},{"text":"AdMetadata","kind":"typeIdentifier","preciseIdentifier":"s:9AdSDKCore0A8MetadataC"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdEvent\/impression(url:metadata:)","kind":"symbol","title":"AdEvent.impression(url:metadata:)"},"doc://com.adsdk.core/documentation/AdSDKCore/AdSDKSwiftUI":{"role":"article","abstract":[{"type":"text","text":"This framework contains the SwiftUI extensions for the AdSDK for iOS. You use this framework together with "},{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore","isActive":true},{"text":".","type":"text"}],"kind":"article","title":"AdSDKSwiftUI","type":"topic","url":"\/documentation\/adsdkcore\/adsdkswiftui","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdSDKSwiftUI"},"doc://com.adsdk.core/documentation/AdSDKCore/AdState":{"title":"AdState","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AdState"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AdState","kind":"identifier"}],"type":"topic","url":"\/documentation\/adsdkcore\/adstate","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdState","abstract":[{"text":"A representation of the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/Advertisement"},{"text":" life cycle.","type":"text"}],"kind":"symbol"},"doc://com.adsdk.core/documentation/AdSDKCore/AdController/update(_:_:)":{"required":true,"title":"update(_:_:)","abstract":[{"text":"Passes new data received from the server to the controller.","type":"text"}],"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdController\/update(_:_:)","url":"\/documentation\/adsdkcore\/adcontroller\/update(_:_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"update","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:9AdSDKCore0A8MetadataC","text":"AdMetadata"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.adsdk.core/documentation/AdSDKCore/AdService":{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService","type":"topic","role":"symbol","url":"\/documentation\/adsdkcore\/adservice","abstract":[{"text":"A key object for configuring your advertisements.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AdService"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AdService"}],"title":"AdService"},"doc://com.adsdk.core/documentation/AdSDKCore/TapEvent/tapAsset(id:)":{"abstract":[{"type":"text","text":"An event that handles the tap on the specific ad banner by the user. Typically"},{"type":"text","text":" "},{"text":"used when a renderer has multiple banners.","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/adsdkcore\/tapevent\/tapasset(id:)","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/TapEvent\/tapAsset(id:)","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tapAsset"},{"kind":"text","text":"("},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"title":"TapEvent.tapAsset(id:)"},"doc://com.adsdk.core/documentation/AdSDKCore/AdRequest/GlobalParameters":{"title":"AdRequest.GlobalParameters","url":"\/documentation\/adsdkcore\/adrequest\/globalparameters","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"An object for storing global parameters that will be applied when creating an"},{"type":"text","text":" "},{"isActive":true,"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest","type":"reference"},{"text":".","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"GlobalParameters","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GlobalParameters"}],"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest\/GlobalParameters"},"doc://com.adsdk.core/documentation/AdSDKCore/AdSDKCoreVersionString":{"title":"AdSDKCoreVersionString","role":"symbol","fragments":[{"kind":"identifier","text":"AdSDKCoreVersionString"}],"type":"topic","url":"\/documentation\/adsdkcore\/adsdkcoreversionstring","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdSDKCoreVersionString","abstract":[{"type":"text","text":"Project version string for AdSDKCore."}],"kind":"symbol"},"doc://com.adsdk.core/documentation/AdSDKCore/AdError":{"type":"topic","title":"AdError","navigatorTitle":[{"text":"AdError","kind":"identifier"}],"abstract":[{"text":"Type of SDK-related error.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdError","url":"\/documentation\/adsdkcore\/aderror","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AdError","kind":"identifier"}]},"doc://com.adsdk.core/documentation/AdSDKCore/TargetURLHandler":{"abstract":[{"text":"The protocol of object responsible for processing the URL that the SDK wants to open","type":"text"},{"text":" ","type":"text"},{"text":"in the browser.","type":"text"}],"navigatorTitle":[{"text":"TargetURLHandler","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/adsdkcore\/targeturlhandler","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/TargetURLHandler","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"TargetURLHandler","kind":"identifier"}],"title":"TargetURLHandler"},"doc://com.adsdk.core/documentation/AdSDKCore/AdVisibilityPercentage":{"abstract":[{"type":"text","text":"Representation of the percentage of visibility of the advertisement on the screen."}],"navigatorTitle":[{"text":"AdVisibilityPercentage","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdVisibilityPercentage","kind":"symbol","url":"\/documentation\/adsdkcore\/advisibilitypercentage","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdVisibilityPercentage","kind":"identifier"}],"title":"AdVisibilityPercentage"},"doc://com.adsdk.core/documentation/AdSDKCore/TapEvent/silentTap(_:)":{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/TapEvent\/silentTap(_:)","title":"TapEvent.silentTap(_:)","role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"silentTap"},{"kind":"text","text":"("},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":")"}],"type":"topic","abstract":[{"text":"An event that can trigger a redirect process without the user’s knowledge","type":"text"},{"type":"text","text":" "},{"type":"text","text":"when tapping on an ad."}],"url":"\/documentation\/adsdkcore\/tapevent\/silenttap(_:)"},"doc://com.adsdk.core/documentation/AdSDKCore/AdEvent/unloadRequest":{"kind":"symbol","abstract":[{"type":"text","text":"Signals that the renderer wants to be unloaded."}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unloadRequest"}],"type":"topic","url":"\/documentation\/adsdkcore\/adevent\/unloadrequest","title":"AdEvent.unloadRequest","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdEvent\/unloadRequest"},"doc://com.adsdk.core/tutorials/Meet-AdSDK":{"title":"Meet nextgen AdSDK","kind":"overview","identifier":"doc:\/\/com.adsdk.core\/tutorials\/Meet-AdSDK","role":"overview","type":"topic","url":"\/tutorials\/meet-adsdk","abstract":[{"type":"text","text":"Manage, display, and create your custom advertisements on iOS using cutting-edge technologies such as Combine, Modern Concurrency, and SwiftUI based on the AdSDK."}]},"doc://com.adsdk.core/documentation/AdSDKCore/AdSDKSwiftUI#AdService-creation-for-SwiftUI":{"url":"\/documentation\/adsdkcore\/adsdkswiftui#AdService-creation-for-SwiftUI","title":"AdService creation for SwiftUI","type":"topic","abstract":[],"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdSDKSwiftUI#AdService-creation-for-SwiftUI","kind":"section"},"doc://com.adsdk.core/documentation/AdSDKCore/AdRequest/campaignId":{"title":"campaignId","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"campaignId","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/adsdkcore\/adrequest\/campaignid","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest\/campaignId","abstract":[{"type":"text","text":"The SDK provides functionality to request a specific campaign from the backend."},{"type":"text","text":" "},{"type":"text","text":"This could be helpful for debugging and testing purposes."}],"kind":"symbol"},"doc://com.adsdk.core/documentation/AdSDKCore/AdRequest/GlobalParameters/isSHBEnabled":{"title":"isSHBEnabled","abstract":[{"type":"text","text":"Defines, if the request should also consider the server side header bidding."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isSHBEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?"}],"type":"topic","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest\/GlobalParameters\/isSHBEnabled","kind":"symbol","role":"symbol","url":"\/documentation\/adsdkcore\/adrequest\/globalparameters\/isshbenabled"},"doc://com.adsdk.core/documentation/AdSDKCore/AdService/tagUser(request:)-2remz":{"title":"tagUser(request:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tagUser"},{"kind":"text","text":"("},{"text":"request","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TagRequest","preciseIdentifier":"s:9AdSDKCore10TagRequestV"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:7Combine12AnyPublisherV","kind":"typeIdentifier","text":"AnyPublisher"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s5NeverO","text":"Never","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"AdError","kind":"typeIdentifier","preciseIdentifier":"s:9AdSDKCore0A5ErrorO"},{"kind":"text","text":">"}],"type":"topic","url":"\/documentation\/adsdkcore\/adservice\/taguser(request:)-2remz","abstract":[{"type":"text","text":"Trigger a request to “tag” a user."}],"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService\/tagUser(request:)-2remz","kind":"symbol"},"doc://com.adsdk.core/documentation/AdSDKCore/AdRequest/GlobalParameters/gdpr":{"url":"\/documentation\/adsdkcore\/adrequest\/globalparameters\/gdpr","type":"topic","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest\/GlobalParameters\/gdpr","abstract":[{"type":"text","text":"App can ask users about their consent for sharing information with third parties."},{"type":"text","text":" "},{"type":"text","text":"The SDK can forward users preferences if they follow the TCF format,"},{"text":" ","type":"text"},{"type":"text","text":"see this "},{"isActive":true,"type":"reference","identifier":"https:\/\/iabeurope.eu\/transparency-consent-framework\/"}],"kind":"symbol","title":"gdpr","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gdpr","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:9AdSDKCore0A7RequestV4GDPRV","text":"GDPR"},{"text":"?","kind":"text"}],"role":"symbol"},"doc://com.adsdk.core/documentation/AdSDKCore/AdEvent/customRendererEvent(name:url:info:metadata:)":{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdEvent\/customRendererEvent(name:url:info:metadata:)","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"customRendererEvent"},{"text":"(","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"url","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"text":"?, ","kind":"text"},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"metadata","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:9AdSDKCore0A8MetadataC","text":"AdMetadata"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Signals that the renderer has passed a custom event."}],"url":"\/documentation\/adsdkcore\/adevent\/customrendererevent(name:url:info:metadata:)","kind":"symbol","role":"symbol","title":"AdEvent.customRendererEvent(name:url:info:metadata:)"},"doc://com.adsdk.core/documentation/AdSDKCore/Advertisement/statePublisher":{"kind":"symbol","url":"\/documentation\/adsdkcore\/advertisement\/statepublisher","type":"topic","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/Advertisement\/statePublisher","required":true,"title":"statePublisher","abstract":[{"text":"Advertisement state publisher.","type":"text"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"statePublisher","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7Combine12AnyPublisherV","text":"AnyPublisher"},{"kind":"text","text":"<"},{"text":"AdState","kind":"typeIdentifier","preciseIdentifier":"s:9AdSDKCore0A5StateO"},{"kind":"text","text":", "},{"preciseIdentifier":"s:s5NeverO","kind":"typeIdentifier","text":"Never"},{"text":">","kind":"text"}]},"https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests":{"url":"https:\/\/developer.apple.com\/documentation\/bundleresources\/privacy_manifest_files\/describing_data_use_in_privacy_manifests","titleInlineContent":[{"type":"text","text":"documentation"}],"title":"documentation","type":"link","identifier":"https:\/\/developer.apple.com\/documentation\/bundleresources\/privacy_manifest_files\/describing_data_use_in_privacy_manifests"},"doc://com.adsdk.core/documentation/AdSDKCore/AdState/loading":{"title":"AdState.loading","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"loading"}],"type":"topic","url":"\/documentation\/adsdkcore\/adstate\/loading","abstract":[{"type":"text","text":"Signals that the advertisement data is currently being loaded from the server."}],"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdState\/loading","kind":"symbol"},"doc://com.adsdk.core/documentation/AdSDKCore/AdRenderer":{"navigatorTitle":[{"kind":"identifier","text":"AdRenderer"}],"abstract":[{"type":"text","text":"Custom renderer interface."}],"url":"\/documentation\/adsdkcore\/adrenderer","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRenderer","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"AdRenderer","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","title":"AdRenderer"},"doc://com.adsdk.core/documentation/AdSDKCore/AdService/trackRequest(_:)-9icj3":{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService\/trackRequest(_:)-9icj3","url":"\/documentation\/adsdkcore\/adservice\/trackrequest(_:)-9icj3","kind":"symbol","role":"symbol","abstract":[{"text":"Trigger a request for conversion tracking.","type":"text"}],"title":"trackRequest(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackRequest"},{"kind":"text","text":"("},{"preciseIdentifier":"s:9AdSDKCore12TrackRequestV","text":"TrackRequest","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"AnyPublisher","kind":"typeIdentifier","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s5NeverO","text":"Never","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"AdError","kind":"typeIdentifier","preciseIdentifier":"s:9AdSDKCore0A5ErrorO"},{"kind":"text","text":">"}],"type":"topic"},"doc://com.adsdk.core/documentation/AdSDKCore/Advertisement":{"navigatorTitle":[{"text":"Advertisement","kind":"identifier"}],"role":"symbol","url":"\/documentation\/adsdkcore\/advertisement","kind":"symbol","type":"topic","abstract":[{"text":"A key object interface describing the advertisement.","type":"text"}],"title":"Advertisement","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/Advertisement","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"Advertisement","kind":"identifier"}]},"doc://com.adsdk.core/documentation/AdSDKCore/AdService/tagUser(request:)-4qs0m":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tagUser"},{"kind":"text","text":"("},{"text":"request","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TagRequest","preciseIdentifier":"s:9AdSDKCore10TagRequestV"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"}],"type":"topic","title":"tagUser(request:)","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService\/tagUser(request:)-4qs0m","role":"symbol","abstract":[{"type":"text","text":"Trigger a request to “tag” a user."}],"url":"\/documentation\/adsdkcore\/adservice\/taguser(request:)-4qs0m"},"doc://com.adsdk.core/documentation/AdSDKCore/AdState/readyToPresent(metadata:)":{"title":"AdState.readyToPresent(metadata:)","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"readyToPresent"},{"kind":"text","text":"("},{"text":"metadata","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdMetadata","preciseIdentifier":"s:9AdSDKCore0A8MetadataC"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/adsdkcore\/adstate\/readytopresent(metadata:)","abstract":[{"type":"text","text":"Signals that the advertisement is now ready to be displayed for the user."}],"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdState\/readyToPresent(metadata:)","kind":"symbol"},"doc://com.adsdk.core/documentation/AdSDKCore/TapEvent/tapURL(_:)":{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/TapEvent\/tapURL(_:)","url":"\/documentation\/adsdkcore\/tapevent\/tapurl(_:)","type":"topic","kind":"symbol","title":"TapEvent.tapURL(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"tapURL","kind":"identifier"},{"text":"(","kind":"text"},{"text":"TapURL","kind":"typeIdentifier","preciseIdentifier":"s:9AdSDKCore6TapURLV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"An event that handles the tap on the ad by the user."}]},"doc://com.adsdk.core/documentation/AdSDKCore/AssetRequest":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Describes a request to load an asset."}],"role":"symbol","title":"AssetRequest","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AssetRequest"}],"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AssetRequest","navigatorTitle":[{"text":"AssetRequest","kind":"identifier"}],"url":"\/documentation\/adsdkcore\/assetrequest"},"doc://com.adsdk.core/documentation/AdSDKCore/AdEvent":{"title":"AdEvent","role":"symbol","navigatorTitle":[{"text":"AdEvent","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AdEvent","kind":"identifier"}],"type":"topic","url":"\/documentation\/adsdkcore\/adevent","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdEvent","abstract":[{"type":"text","text":"A representation of the "},{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/Advertisement","isActive":true,"type":"reference"},{"text":" events.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.adsdk.core\/tutorials\/Meet-AdSDK","doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdSDKSwiftUI"],"anchor":"Essentials","title":"Essentials"},{"generated":true,"title":"Variables","anchor":"Variables","identifiers":["doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdSDKCoreVersionNumber","doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdSDKCoreVersionString"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null}]}]}