{"hierarchy":{"paths":[["doc:\/\/com.adsdk.core\/documentation\/AdSDKCore"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/adsdkcore\/adsdkswiftui"]},{"paths":["\/documentation\/adsdkcore\/adsdkswiftui"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"article","modules":[{"name":"AdSDKCore"}],"title":"AdSDKSwiftUI","roleHeading":"Article"},"seeAlsoSections":[{"generated":true,"title":"Essentials","identifiers":["doc:\/\/com.adsdk.core\/tutorials\/Meet-AdSDK","doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService","doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/Advertisement"]}],"kind":"article","sections":[],"abstract":[{"type":"text","text":"This framework contains the SwiftUI extensions for the AdSDK for iOS. You use this framework together with "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore"},{"type":"text","text":"."}],"identifier":{"url":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdSDKSwiftUI","interfaceLanguage":"swift"},"primaryContentSections":[{"content":[{"type":"heading","level":2,"anchor":"Overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"On top of the SDK Core, "},{"type":"codeVoice","code":"AdSDKSwiftUI"},{"type":"text","text":" provides extensions for displaying "},{"isActive":true,"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/Advertisement","type":"reference"},{"text":" in SwiftUI based applications.","type":"text"}]},{"inlineContent":[{"type":"text","text":"The currently available inline renderers are:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"inlineContent":[{"type":"text","text":"Native Image"}],"type":"strong"},{"text":" – displays the image received from the ad server, responds to events related to display and interactions with the advertisement.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"type":"text","text":"Generic"}],"type":"strong"},{"type":"text","text":" – displays advertisements in HTML format using "},{"type":"codeVoice","code":"WKWebView"},{"type":"text","text":" and has limited support for MRAID 3.0. For clarification on supported functionality, please contact the mobile team at ADITION."}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The currently available interstitial renderers are:"}]},{"items":[{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Interstitial Image"}]},{"type":"text","text":" – displays an advertising image received from the server in full screen, which will disappear after a certain period of time, which you can configure on the frontend."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"type":"text","text":"Interstitial Image with Close Button"}],"type":"strong"},{"type":"text","text":" – displays an advertising image received from the server in full screen, on which a button to close will appear after a certain period of time. You can configure the time after which the button should appear and the image of the button itself in the frontend."}]}]}],"type":"unorderedList"},{"anchor":"AdService-creation-for-SwiftUI","text":"AdService creation for SwiftUI","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To easily create and configure an "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService"},{"text":" in your application that uses ","type":"text"},{"code":"SwiftUI","type":"codeVoice"},{"type":"text","text":", the "},{"code":"AdSDKSwiftUI","type":"codeVoice"},{"type":"text","text":" framework has a static methods for "},{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService","isActive":true},{"type":"text","text":" creation."}]},{"type":"codeListing","syntax":"swift","code":["static func configure(","    networkID: UInt,","    cacheSize: UInt8 = 100,","    timeout: Int = 60",") -> AnyPublisher<AdService, AdError>","","static func configure(","    networkID: UInt,","    cacheSize: UInt8 = 100,","    timeout: Int = 60",") async throws -> AdService"]},{"type":"paragraph","inlineContent":[{"inlineContent":[{"type":"text","text":"Parameters:"}],"type":"strong"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"networkID: Appropriate ","type":"text"},{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService\/networkID","isActive":true,"type":"reference"},{"text":".","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"cacheSize: Size in mb that you can set for max cache size. 100 Mb by default."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"timeout: Timeout defines the time interval to setup the config. 60 seconds by default."}],"type":"paragraph"}]}]},{"inlineContent":[{"type":"strong","inlineContent":[{"text":"Returns:","type":"text"}]},{"text":" Configured ","type":"text"},{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"paragraph"},{"code":["\/\/ Combine","subscription = AdService.configure(networkID: 0000)","    .sink { [unowned self] completion in","        guard case .failure(let error) = completion else { return }","","        print(\"AdService configuration error: \\(error)\")","","    } receiveValue: { [unowned self] adService in","        print(\"AdService configured and ready to work\")","    }","","\/\/ Async\/Await","do {","    let adService = try await AdService.configure(","        networkID: 0000","    )","","    print(\"AdService configured and ready to work\")","","} catch {","    print(\"AdService configuration error: \\(error)\")","}"],"syntax":"swift","type":"codeListing"},{"level":2,"anchor":"Displaying-Inline-Advertisements","type":"heading","text":"Displaying Inline Advertisements"},{"inlineContent":[{"type":"text","text":"To display advertisements in your SwiftUI hierarchy, you use "},{"type":"codeVoice","code":"AdView"},{"type":"text","text":". It serves as a container for any type of inline advertisement, both built-in and custom native."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"text":"Important:","type":"text"}]},{"text":" ","type":"text"},{"type":"codeVoice","code":"AdView"},{"text":" can only display Ads with the ","type":"text"},{"code":"placementType","type":"codeVoice"},{"type":"text","text":" parameter "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdPlacementType\/inline"},{"text":".","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"If you pass to it:","type":"text"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/Advertisement","isActive":true},{"type":"text","text":" with the "},{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdPlacementType\/interstitial","isActive":true},{"type":"text","text":" parameter, the ad will not be displayed and you will see an error in the debug section of your IDE."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/Advertisement","isActive":true,"type":"reference"},{"type":"text","text":" with a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest\/contentUnit"},{"type":"text","text":" that returns "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdPlacementType\/interstitial"},{"text":" - the advertisement will return an ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdState\/error(_:)","isActive":true},{"type":"text","text":" state with an "},{"isActive":true,"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdError\/mismatchPlacementType","type":"reference"},{"text":" error.","type":"text"}]}]}],"type":"unorderedList"},{"type":"codeListing","syntax":"swift","code":["@Observable","@MainActor","final class AdCellViewModel {","    var ad: Advertisement","    var state: State = .loading","","    init(request: AdRequest, _ service: AdService) {","        self.ad = service.makeAdvertisement(","            request: request,","            \/\/ The inline parameter is the default,","            \/\/ so you do not need to specify it explicitly.","            placementType: .inline ","        )","    }","","    \/\/ ...","}","","struct AdCell: View {","    @State var viewModel: AdCellViewModel","","    var body: some View {","        switch viewModel.state {","        case .loading:","            loaderView()","","        case .view(let advertisement):","            AdView(advertisement: advertisement)","","        case .error(let description):","            errorView(description)","        }","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can also calculate the size of the ad based on the aspect ratio. See how "},{"code":"AdView","type":"codeVoice"},{"type":"text","text":" works in practice in the "},{"isActive":true,"type":"reference","overridingTitleInlineContent":[{"text":"tutorial","type":"text"}],"identifier":"doc:\/\/com.adsdk.core\/tutorials\/Meet-AdSDK","overridingTitle":"tutorial"},{"text":".","type":"text"}]},{"anchor":"Displaying-Interstitial-Advertisements","level":2,"text":"Displaying Interstitial Advertisements","type":"heading"},{"inlineContent":[{"text":"To display ads in full screen, you use the ","type":"text"},{"type":"codeVoice","code":".interstitial(isShouldBePresented:,_:)"},{"type":"text","text":" View modifier. It serves as a container for any type of interstitial advertisement, both built-in and custom native."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"Important:","type":"text"}],"type":"strong"},{"type":"text","text":" "},{"type":"codeVoice","code":".interstitial(isShouldBePresented:,_:)"},{"type":"text","text":" can only display Ads with the "},{"code":"placementType","type":"codeVoice"},{"text":" parameter ","type":"text"},{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdPlacementType\/interstitial","isActive":true,"type":"reference"},{"type":"text","text":"."}]},{"inlineContent":[{"type":"text","text":"If you pass to it:"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/Advertisement","isActive":true,"type":"reference"},{"type":"text","text":" with the "},{"isActive":true,"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdPlacementType\/inline","type":"reference"},{"type":"text","text":" parameter, the ad will not be displayed and you will see an error in the debug section of your IDE."}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/Advertisement","type":"reference","isActive":true},{"text":" with a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest\/contentUnit","isActive":true},{"text":" that returns ","type":"text"},{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdPlacementType\/inline","isActive":true,"type":"reference"},{"type":"text","text":" - the advertisement will return an "},{"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdState\/error(_:)","isActive":true,"type":"reference"},{"type":"text","text":" state with an "},{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdError\/mismatchPlacementType","isActive":true},{"type":"text","text":" error."}],"type":"paragraph"}]}],"type":"unorderedList"},{"type":"codeListing","code":["@Observable","@MainActor","final class ScreenWithInterstitialViewModel {","    var ad: Advertisement","    var isInterstitialPresented: Bool = false","","    init(request: AdRequest, _ service: AdService) {","        self.ad = service.makeAdvertisement(","            request: request,","            placementType: .interstitial","        )","","        observeAd(ad)","    }","","    func observeAd(_ ad: Advertisement) {","        Task {","            for await state in ad.stateStream {","                guard case .readyToPresent(let metadata) = state else {","                    return","                }","","                \/\/ After receiving readyToPresent state you can","                \/\/ start to present interstitial.","                \/\/","                \/\/ If you change the state to true before the ad","                \/\/ is loaded, it will be displayed immediately after","                \/\/ it is loaded.","                isInterstitialPresented = true","            }","        }","    }","}","","struct ScreenWithInterstitial: View {","    @State var viewModel: ScreenWithInterstitialViewModel","","    var body: some View {","        VStack {","            Text(\"My Screen Content\")","        }","        .interstitial(","            isShouldBePresented: $viewModel.isInterstitialPresented,","            viewModel.ad","        )","    }","}"],"syntax":"swift"},{"type":"heading","text":"Visibility events","anchor":"Visibility-events","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"To enable the partial visibility events "},{"type":"reference","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdEvent\/viewable(percentage:url:metadata:)","isActive":true},{"type":"text","text":" with inline ad, you have to add the "},{"code":".adsContainer()","type":"codeVoice"},{"type":"text","text":" View modifier:"}]},{"code":["var body: some View {","    List {","        ForEach(cellViewModels) {","            AdCell(viewModel: $0)","        }","    }","    .clipped()","    .adsContainer()","}"],"syntax":"swift","type":"codeListing"}],"kind":"content"}],"references":{"doc://com.adsdk.core/documentation/AdSDKCore/AdPlacementType/inline":{"type":"topic","title":"AdPlacementType.inline","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"inline","kind":"identifier"}],"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdPlacementType\/inline","abstract":[],"kind":"symbol","url":"\/documentation\/adsdkcore\/adplacementtype\/inline"},"doc://com.adsdk.core/documentation/AdSDKCore":{"type":"topic","role":"collection","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore","abstract":[{"type":"text","text":"Manage, display, and create your custom advertisements on iOS using cutting-edge technologies such as Combine, Modern Concurrency, and SwiftUI based."}],"kind":"symbol","title":"AdSDKCore","url":"\/documentation\/adsdkcore"},"doc://com.adsdk.core/documentation/AdSDKCore/AdState/error(_:)":{"type":"topic","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdState\/error(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"error","kind":"identifier"},{"kind":"text","text":"("},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Signals that an advertisement lifecycle error has occurred.","type":"text"}],"title":"AdState.error(_:)","url":"\/documentation\/adsdkcore\/adstate\/error(_:)"},"doc://com.adsdk.core/documentation/AdSDKCore/AdService/networkID":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkID"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"role":"symbol","title":"networkID","kind":"symbol","abstract":[{"type":"text","text":"The unique identifier of the ad network."}],"url":"\/documentation\/adsdkcore\/adservice\/networkid","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService\/networkID","type":"topic"},"doc://com.adsdk.core/tutorials/Meet-AdSDK":{"role":"overview","title":"Meet nextgen AdSDK","url":"\/tutorials\/meet-adsdk","kind":"overview","type":"topic","identifier":"doc:\/\/com.adsdk.core\/tutorials\/Meet-AdSDK","abstract":[{"text":"Manage, display, and create your custom advertisements on iOS using cutting-edge technologies such as Combine, Modern Concurrency, and SwiftUI based on the AdSDK.","type":"text"}]},"doc://com.adsdk.core/documentation/AdSDKCore/AdRequest/contentUnit":{"kind":"symbol","url":"\/documentation\/adsdkcore\/adrequest\/contentunit","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"contentUnit","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"abstract":[{"text":"Unique ID of a content space in the ADITION ad-serving platform.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdRequest\/contentUnit","title":"contentUnit"},"doc://com.adsdk.core/documentation/AdSDKCore/AdEvent/viewable(percentage:url:metadata:)":{"type":"topic","url":"\/documentation\/adsdkcore\/adevent\/viewable(percentage:url:metadata:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"viewable","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"percentage"},{"text":": ","kind":"text"},{"text":"AdVisibilityPercentage","preciseIdentifier":"s:9AdSDKCore0A20VisibilityPercentageO","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"url","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"metadata"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:9AdSDKCore0A8MetadataC","text":"AdMetadata"},{"kind":"text","text":")"}],"abstract":[{"text":"Signals that the user has seen an advertisement.","type":"text"}],"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdEvent\/viewable(percentage:url:metadata:)","title":"AdEvent.viewable(percentage:url:metadata:)"},"doc://com.adsdk.core/documentation/AdSDKCore/AdService":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AdService","kind":"identifier"}],"title":"AdService","role":"symbol","identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdService","type":"topic","url":"\/documentation\/adsdkcore\/adservice","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AdService"}],"abstract":[{"type":"text","text":"A key object for configuring your advertisements."}]},"doc://com.adsdk.core/documentation/AdSDKCore/Advertisement":{"url":"\/documentation\/adsdkcore\/advertisement","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Advertisement"}],"kind":"symbol","title":"Advertisement","role":"symbol","abstract":[{"text":"A key object interface describing the advertisement.","type":"text"}],"navigatorTitle":[{"text":"Advertisement","kind":"identifier"}],"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/Advertisement","type":"topic"},"doc://com.adsdk.core/documentation/AdSDKCore/AdPlacementType/interstitial":{"abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"interstitial"}],"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdPlacementType\/interstitial","role":"symbol","title":"AdPlacementType.interstitial","kind":"symbol","url":"\/documentation\/adsdkcore\/adplacementtype\/interstitial","type":"topic"},"doc://com.adsdk.core/documentation/AdSDKCore/AdError/mismatchPlacementType":{"title":"AdError.mismatchPlacementType","abstract":[{"type":"text","text":"The error is caused by an incorrect match between the passed and received"},{"type":"text","text":" "},{"type":"text","text":"placement type."}],"identifier":"doc:\/\/com.adsdk.core\/documentation\/AdSDKCore\/AdError\/mismatchPlacementType","url":"\/documentation\/adsdkcore\/aderror\/mismatchplacementtype","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mismatchPlacementType"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":null,"op":"add","path":"\/topicSections"},{"value":[{"title":"Essentials","generated":true,"identifiers":["doc:\/\/com.adsdk.core\/tutorials\/Meet-AdSDK"]}],"op":"replace","path":"\/seeAlsoSections"}]}]}