name: Update & Deploy Documentation
on: 
  repository_dispatch:
    types: [doc-update-trigger]
permissions:
  contents: write
jobs:
  doc_update:
    name: Process zip doc archive
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: gh_pages_test
      - name: Check branch
        run: |
          git branch --show-current
      - name: Load documentation
        run: |
          repo_owner="VM-Mobile-SDK"
          repo_name="nextgen-adsdk-ios"
          artifact_id="${{ github.event.client_payload.artifact_id }}"
          api_url="https://api.github.com/repos/$repo_owner/$repo_name/actions/artifacts/$artifact_id/zip"
          doc_version="${{ github.event.client_payload.release_number }}"
          output="./docs/${{ github.event.client_payload.release_number }}.zip"

          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "$api_url" -o "$output" || exit 1

          unzip "$output" && rm "$output"
      - name: Upload doc for test
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.client_payload.release_number }}
          path: "./docs/${{ github.event.client_payload.release_number }}"