name: Update Documentation
on: 
  repository_dispatch:
    types: [doc-update-trigger]
permissions:
  contents: write
jobs:
  doc_update:
    name: Update documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: gh_pages_test
      - name: Load documentation
        run: |
          repo_owner="VM-Mobile-SDK"
          repo_name="nextgen-adsdk-ios"
          artifact_id="${{ github.event.client_payload.artifact_id }}"
          api_url="https://api.github.com/repos/$repo_owner/$repo_name/actions/artifacts/$artifact_id/zip"
          doc_version="${{ github.event.client_payload.release_number }}"

          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "$api_url" -o "doc.zip" || exit 1
            
          unzip -o "doc.zip"
          unzip -o "$doc_version.zip" -d "docs/"
          rm "doc.zip" & rm "$doc_version.zip"
      - name: Update documentation
        run: |
          cd scripts
          sh update_doc_versions.sh 5
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: mobilesdk
          author_email: mobilesdk@virtualminds.com
          message: 'Documentation updated'