name: Update & Deploy SPM, Pods, Doc
on:
  push:
    tags:
      - "*.*.*"
permissions:
  contents: write
jobs:
  update_spm_and_podspecs:
    name: Update SPM & Podspecs
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Update package
        run: |
          echo "::group::determining release tag"
          ref=${{ github.ref }} 
          release_tag="${ref##*refs/tags/}" 
          echo "tag=$release_tag" >> "$GITHUB_ENV"
          echo $release_tag
          echo "::endgroup::"
          
          echo "::group::update_release_files.sh"
          sh ./update_release_files.sh $release_tag AdSDKCore "AdSDKCore-$release_tag.zip" AdSDKSwiftUI "AdSDKSwiftUI-$release_tag.zip"
          echo "::endgroup::"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: mobilesdk_github_action
          author_email: mobilesdk@virtualminds.com
          message: 'Updated SPM and podspecs definition.'
          add: |
            - Package.swift
            - AdSDKCore.podspec
            - AdSDKSwiftUI.podspec
          tag: ${{ env.tag }} --force
          push: origin HEAD:main
          tag_push: --force
      - name: Install Cocoapods
        run: gem install cocoapods
      - name: Cocoapods Trunk Release
        uses: michaelhenry/deploy-to-cocoapods-github-action@1.0.10
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
  deploy_docs:
    name: Deploy Docs
    runs-on: ubuntu-latest
    needs: update_spm_and_podspecs
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get docs artifact
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: "docs.zip"
          token: ${{ secrets.GH_TOKEN }}
      - name: Switch to gh_pages branch
        run: |
          git config --global user.email "mobilesdk@virtualminds.com"
          git config --global user.name "mobilesdk_github_action"
          git fetch origin gh_pages:gh_pages
          git checkout gh_pages
          git pull --rebase origin gh_pages
      - name: Update docs folder
        run: |
          rm -r docs
          unzip docs.zip -d ./
          rm docs.zip
      - name: Commit and push changes to gh_pages
        run: |
          git add docs
          git commit -m "Update online documentation for the version: ${{ github.ref_name }}"
          git push -u origin gh_pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}